* added more logging to configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -46,11 +46,13 @@ else
 fi
 
 add_line_to_makefile_local() {
+	echo "Makefile.local => $1" >> config.log
 	makefile_local_data="${makefile_local_data}"'
 '"$1"
 }
 
 error() {
+	echo "ERROR: $@" >> config.log
 	echo $@
 	exit 1
 }
@@ -60,6 +62,7 @@ error() {
 # @param 3 The text that is written to the console on failure
 # @param 4 If 'yes' is given here, the variable must be set in order to let configure continue
 add_to_makefile_local_quote() {
+	echo "add_to_makefile_local_quote => $@" >> config.log
 	VALUE=`get_var $1`
 	if [ -n "$VALUE" ]; then
 		# these are internal make variables and are already set, so don't use ?= here
@@ -81,6 +84,7 @@ add_to_makefile_local_quote() {
 # @param 3 The text that is written to the console on failure
 # @param 4 If 'yes' is given here, the variable must be set in order to let configure continue
 add_to_makefile_local() {
+	echo "add_to_makefile_local => $@" >> config.log
 	VALUE=`get_var $1`
 	if [ -n "$VALUE" ]; then
 		# these are internal make variables and are already set, so don't use ?= here
@@ -98,11 +102,13 @@ add_to_makefile_local() {
 }
 
 add_line_to_config_h() {
+	echo "config.h => $1" >> config.log
 	config_h_data="${config_h_data}"'
 '"$1"
 }
 
 add_to_config_h_quote() {
+	echo "add_to_config_h_quote => $@" >> config.log
 	VALUE=`get_var $1`
 	if [ -n "$VALUE" ] && [ "$VALUE" != "0" ]; then
 		add_line_to_config_h "#define $1 \"$VALUE\""
@@ -115,6 +121,7 @@ add_to_config_h_quote() {
 }
 
 add_to_config_h() {
+	echo "add_to_config_h => $@" >> config.log
 	VALUE=`get_var $1`
 	if [ -n "$VALUE" ] && [ "$VALUE" != "0" ]; then
 		add_line_to_config_h "#define $1 $VALUE"
@@ -182,6 +189,8 @@ int main (int argc, char *argv[]) {
 	return EXIT_SUCCESS;
 }
 EOF`
+	echo "$SOURCE" >> config.log
+	echo "${CROSS}${CXX} ${3} ${CCFLAGS} ${CXXFLAGS} ${CFLAGS} -o /dev/null -xc++" >> config.log
 	( echo "$SOURCE" | ${CROSS}${CXX} ${3} ${CCFLAGS} ${CXXFLAGS} ${CFLAGS} -o /dev/null -xc++ - 2>> config.log ) && echo "1" || echo ""
 }
 
@@ -203,9 +212,14 @@ check_header_cc() {
 #include <stdio.h>
 #include <${1}>
 EOF`
+	echo "$SOURCE" >> config.log
 	if [ -n "${2}" ]; then
-		( echo "$SOURCE" | ${CROSS}${CXX} ${CCFLAGS} ${CXXFLAGS} ${CFLAGS} $(${CROSS}pkg-config --cflags ${2} 2> /dev/null) -o /dev/null -xc++ -c - 2>> config.log ) && echo "1" || echo ""
+		PKG_FLAGS=$(${CROSS}pkg-config --cflags ${2} 2>> config.log)
+		echo "pkg-config => ${PKG_FLAGS}" >> config.log
+		echo "${CROSS}${CXX} ${CCFLAGS} ${CXXFLAGS} ${CFLAGS} ${PKG_FLAGS} -o /dev/null -xc++" >> config.log
+		( echo "$SOURCE" | ${CROSS}${CXX} ${CCFLAGS} ${CXXFLAGS} ${CFLAGS} ${PKG_FLAGS} -o /dev/null -xc++ -c - 2>> config.log ) && echo "1" || echo ""
 	else
+		echo "${CROSS}${CXX} ${CCFLAGS} ${CXXFLAGS} ${CFLAGS} -o /dev/null -xc++" >> config.log
 		( echo "$SOURCE" | ${CROSS}${CXX} ${CCFLAGS} ${CXXFLAGS} ${CFLAGS} -o /dev/null -xc++ -c - 2>> config.log ) && echo "1" || echo ""
 	fi
 }
@@ -361,10 +375,12 @@ make_var() {
 }
 
 set_var() {
+	echo "set_var $1 = $2" >> config.log
 	eval `make_var "$1"`=\""$2"\"
 }
 
 get_var() {
+	echo "get_var $1 = $(eval echo \${`make_var "$1"`})" >> config.log
 	eval echo \${`make_var "$1"`}
 }
 
